[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = [
  "php83",
  "php83Extensions.pdo_pgsql",
  "php83Extensions.pgsql"
]

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
preDeployCommand = "php artisan migrate --force"