server {
    listen 80;
    index index.php index.html;
    server_name localhost;

    root /var/www/html/public;

    location /api {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /spa/ {
        try_files $uri $uri/ =404;
    }

    location = /spa/favicon.ico {
        try_files /favicon.ico =404;
    }

    location = /spa/robots.txt {
        try_files /robots.txt =404;
    }

    location / {
        try_files $uri /spa/index.html;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}