<?php

namespace Database\Seeders;

use App\Models\Perfume;
use Illuminate\Database\Seeder;

class PerfumeSeeder extends Seeder
{
    public function run(): void
    {
        $perfumes = [
            [
                'name' => 'Boss Bottled Eau de Parfum',
                'slug' => 'boss-bottled',
                'brand' => 'Hugo Boss',
                'gender' => 'Homme || رجالي',
                'short_description' => 'Boise epice avec pomme croquante, cannelle et vanille. || خشبي متبّل مع تفاح مقرمش وقرفة وفانيلا.',
                'description' => 'Un classique boise-epice: ouverture fraiche de pomme et agrumes, coeur chaud de cannelle et girofle, puis fond elegant de santal, cedre et vanille. || كلاسيكي خشبي متبّل: افتتاحية منعشة من التفاح والحمضيات، قلب دافئ من القرفة والقرنفل، ثم قاعدة أنيقة من الصندل والأرز والفانيلا.',
                'price' => 89.00,
                'image_url' => null,
                'country_of_origin' => 'Allemagne || ألمانيا',
                'size_options' => ['50ml', '100ml', '200ml'],
                'stock_status' => 'En stock || متوفر',
                'fragrance_family' => 'Boise epice || خشبي متبّل',
                'recipe' => 'Accord signature pomme-cannelle, soutenu par un coeur floral-epice et un fond boise vanille. || تركيبة مميزة من التفاح والقرفة مع قلب زهري-متبّل وقاعدة خشبية فانيليا.',
                'top_notes' => ['Pomme || تفاح', 'Bergamote || برغموت', 'Citron || ليمون'],
                'heart_notes' => ['Cannelle || قرفة', 'Geranium || إبرة الراعي', 'Clou de girofle || قرنفل'],
                'base_notes' => ['Santal || خشب الصندل', 'Cedre || خشب الأرز', 'Vanille || فانيلا', 'Vetiver || فيتيفر'],
                'longevity' => '6-8 heures || 6-8 ساعات',
                'sillage' => 'Modere || متوسط',
                'vibe' => 'Elegant, chaleureux et professionnel || أنيق ودافئ واحترافي',
                'when_to_wear' => 'Automne-hiver, bureau et sorties du soir || الخريف والشتاء، المكتب والخروجات المسائية',
                'feeling' => 'Confiance et distinction || ثقة وتميّز',
                'average_rating' => 4.6,
                'reviews_count' => 214,
                'reviews' => [
                    ['author' => 'Youssef', 'rating' => 5, 'comment' => 'Classique tres fiable pour tous les jours.', 'date' => '2026-04-02'],
                    ['author' => 'Nadia', 'rating' => 4, 'comment' => 'Tres belle cannelle en coeur.', 'date' => '2026-03-25'],
                ],
                'bottle_images' => [null],
                'packaging_images' => [null],
                'lifestyle_images' => [null],
                'ingredients' => ['Alcohol Denat.', 'Parfum', 'Limonene', 'Linalool', 'Citral', 'Coumarin'],
                'delivery_info' => 'Livraison 24-48h partout au Maroc || توصيل خلال 24-48 ساعة في جميع أنحاء المغرب',
                'return_policy' => 'Retour sous 7 jours si le produit est non ouvert || إرجاع خلال 7 أيام إذا كان المنتج غير مفتوح',
                'authenticity_guarantee' => 'Parfum 100% authentique garanti || عطر أصلي 100% مضمون',
                'is_best_seller' => true,
                'is_trending' => true,
                'discount_percentage' => 8,
                'similar_slugs' => ['y-eau-de-parfum', 'azzaro-wanted'],
                'is_active' => true,
            ],
            [
                'name' => 'Invictus Eau de Parfum',
                'slug' => 'invictus',
                'brand' => 'Paco Rabanne',
                'gender' => 'Homme || رجالي',
                'short_description' => 'Fraicheur marine avec pamplemousse et fond ambré boise. || انتعاش بحري مع جريب فروت وقاعدة عنبرية خشبية.',
                'description' => 'Un parfum energique et sportif: attaque agrumee et aquatique, coeur aromatique, puis base boisee ambree qui tient bien sur la peau. || عطر رياضي وحيوي: بداية حمضية مائية، قلب عطري، ثم قاعدة خشبية عنبرية بثبات جيد على البشرة.',
                'price' => 92.00,
                'image_url' => null,
                'country_of_origin' => 'France || فرنسا',
                'size_options' => ['50ml', '100ml', '200ml'],
                'stock_status' => 'En stock || متوفر',
                'fragrance_family' => 'Aquatique boise || مائي خشبي',
                'recipe' => 'Structure marine-agrumes renforcee par des bois secs et une touche ambrée moderne. || بنية عطرية مائية حمضية مدعمة بأخشاب جافة ولمسة عنبرية عصرية.',
                'top_notes' => ['Pamplemousse || جريب فروت', 'Notes marines || نغمات بحرية', 'Mandarine || يوسفي'],
                'heart_notes' => ['Feuille de laurier || ورق الغار', 'Jasmin || ياسمين'],
                'base_notes' => ['Bois de gaïac || خشب الغاياك', 'Patchouli || باتشولي', 'Mousse de chene || طحلب البلوط', 'Ambre gris || عنبر رمادي'],
                'longevity' => '6-8 heures || 6-8 ساعات',
                'sillage' => 'Modere a fort || متوسط إلى فواح',
                'vibe' => 'Sportif, propre et dynamique || رياضي ونظيف وحيوي',
                'when_to_wear' => 'Printemps-ete, journee et sport chic || الربيع والصيف، النهار والستايل الرياضي الأنيق',
                'feeling' => 'Energie et victoire || طاقة وإحساس بالفوز',
                'average_rating' => 4.5,
                'reviews_count' => 189,
                'reviews' => [
                    ['author' => 'Karim', 'rating' => 5, 'comment' => 'Tres frais, ideal apres la douche.', 'date' => '2026-04-01'],
                    ['author' => 'Amine', 'rating' => 4, 'comment' => 'Profil aquatique moderne reussi.', 'date' => '2026-03-21'],
                ],
                'bottle_images' => [null],
                'packaging_images' => [null],
                'lifestyle_images' => [null],
                'ingredients' => ['Alcohol Denat.', 'Parfum', 'Limonene', 'Linalool', 'Citral'],
                'delivery_info' => 'Livraison 24-48h partout au Maroc || توصيل خلال 24-48 ساعة في جميع أنحاء المغرب',
                'return_policy' => 'Retour sous 7 jours si le produit est non ouvert || إرجاع خلال 7 أيام إذا كان المنتج غير مفتوح',
                'authenticity_guarantee' => 'Parfum 100% authentique garanti || عطر أصلي 100% مضمون',
                'is_best_seller' => true,
                'is_trending' => true,
                'discount_percentage' => 10,
                'similar_slugs' => ['dior-sauvage', 'y-eau-de-parfum'],
                'is_active' => true,
            ],
            [
                'name' => 'L Homme Eau de Parfum',
                'slug' => 'l-homme-ysl',
                'brand' => 'Yves Saint Laurent',
                'gender' => 'Homme || رجالي',
                'short_description' => 'Boise aromatique raffine au gingembre, basilic et feve tonka. || خشبي عطري راقٍ بالزنجبيل والريحان وحبوب التونكا.',
                'description' => 'Un style chic et urbain: ouverture vive au gingembre et agrumes, coeur aromatique epice, puis base boisee douce avec tonka et vetiver. || أسلوب أنيق وحضري: افتتاحية نابضة بالزنجبيل والحمضيات، قلب عطري متبّل، ثم قاعدة خشبية ناعمة مع تونكا وفيتيفر.',
                'price' => 94.00,
                'image_url' => null,
                'country_of_origin' => 'France || فرنسا',
                'size_options' => ['60ml', '100ml', '200ml'],
                'stock_status' => 'En stock || متوفر',
                'fragrance_family' => 'Boise aromatique || خشبي عطري',
                'recipe' => 'Accord gingembre-citron en tete, aromaticite verte au coeur, et signature tonka-cedre en fond. || تركيبة زنجبيل-ليمون في المقدمة، قلب عطري أخضر، وتوقيع تونكا-أرز في القاعدة.',
                'top_notes' => ['Gingembre || زنجبيل', 'Bergamote || برغموت', 'Citron || ليمون'],
                'heart_notes' => ['Basilic || ريحان', 'Poivre blanc || فلفل أبيض', 'Feuille de violette || ورق البنفسج'],
                'base_notes' => ['Feve tonka || حبوب التونكا', 'Cedre || خشب الأرز', 'Vetiver || فيتيفر'],
                'longevity' => '6-7 heures || 6-7 ساعات',
                'sillage' => 'Modere || متوسط',
                'vibe' => 'Chic, propre et moderne || شيك ونظيف وعصري',
                'when_to_wear' => 'Quotidien, bureau et sorties en ville || يومي، للمكتب والخروجات',
                'feeling' => 'Elegance discrete || أناقة هادئة',
                'average_rating' => 4.4,
                'reviews_count' => 152,
                'reviews' => [
                    ['author' => 'Rachid', 'rating' => 4, 'comment' => 'Super parfum de bureau.', 'date' => '2026-03-30'],
                    ['author' => 'Othmane', 'rating' => 5, 'comment' => 'Tres classe et facile a porter.', 'date' => '2026-03-14'],
                ],
                'bottle_images' => [null],
                'packaging_images' => [null],
                'lifestyle_images' => [null],
                'ingredients' => ['Alcohol Denat.', 'Parfum', 'Limonene', 'Linalool', 'Coumarin'],
                'delivery_info' => 'Livraison 24-48h partout au Maroc || توصيل خلال 24-48 ساعة في جميع أنحاء المغرب',
                'return_policy' => 'Retour sous 7 jours si le produit est non ouvert || إرجاع خلال 7 أيام إذا كان المنتج غير مفتوح',
                'authenticity_guarantee' => 'Parfum 100% authentique garanti || عطر أصلي 100% مضمون',
                'is_best_seller' => false,
                'is_trending' => true,
                'discount_percentage' => 7,
                'similar_slugs' => ['boss-bottled', 'y-eau-de-parfum'],
                'is_active' => true,
            ],
            [
                'name' => 'Wanted Eau de Parfum',
                'slug' => 'azzaro-wanted',
                'brand' => 'Azzaro',
                'gender' => 'Homme || رجالي',
                'short_description' => 'Oriental boise epice, energique et seduisant. || شرقي خشبي متبّل، حيوي وجذّاب.',
                'description' => 'Wanted propose une ouverture piquante au gingembre et citron, un coeur epice-aromatique, puis un fond tonka ambre boise ideal pour les sorties. || يقدم Wanted افتتاحية لاذعة بالزنجبيل والليمون، قلباً متبّلاً عطرياً، ثم قاعدة تونكا وعنبر وخشب مثالية للخروجات.',
                'price' => 88.00,
                'image_url' => null,
                'country_of_origin' => 'France || فرنسا',
                'size_options' => ['50ml', '100ml', '150ml'],
                'stock_status' => 'En stock || متوفر',
                'fragrance_family' => 'Oriental boise epice || شرقي خشبي متبّل',
                'recipe' => 'Base chaude feve tonka et ambre boise, soutenue par des epices lumineuses en tete et coeur. || قاعدة دافئة من التونكا والعنبر الخشبي مع توابل مضيئة في المقدمة والقلب.',
                'top_notes' => ['Citron || ليمون', 'Gingembre || زنجبيل', 'Lavande || لافندر'],
                'heart_notes' => ['Cardamome || هيل', 'Genièvre || العرعر', 'Pomme || تفاح'],
                'base_notes' => ['Feve tonka || حبوب التونكا', 'Ambre boise || عنبر خشبي', 'Vetiver || فيتيفر'],
                'longevity' => '7-9 heures || 7-9 ساعات',
                'sillage' => 'Fort || فواح',
                'vibe' => 'Charismatique et festif || كاريزمي واحتفالي',
                'when_to_wear' => 'Soiree, automne-hiver || المساء، الخريف والشتاء',
                'feeling' => 'Audace et magnetisme || جرأة وجاذبية',
                'average_rating' => 4.5,
                'reviews_count' => 167,
                'reviews' => [
                    ['author' => 'Mehdi', 'rating' => 5, 'comment' => 'Parfait pour sortir le soir.', 'date' => '2026-04-03'],
                    ['author' => 'Samir', 'rating' => 4, 'comment' => 'Tres bon rapport style/performance.', 'date' => '2026-03-24'],
                ],
                'bottle_images' => [null],
                'packaging_images' => [null],
                'lifestyle_images' => [null],
                'ingredients' => ['Alcohol Denat.', 'Parfum', 'Limonene', 'Linalool', 'Coumarin'],
                'delivery_info' => 'Livraison 24-48h partout au Maroc || توصيل خلال 24-48 ساعة في جميع أنحاء المغرب',
                'return_policy' => 'Retour sous 7 jours si le produit est non ouvert || إرجاع خلال 7 أيام إذا كان المنتج غير مفتوح',
                'authenticity_guarantee' => 'Parfum 100% authentique garanti || عطر أصلي 100% مضمون',
                'is_best_seller' => true,
                'is_trending' => true,
                'discount_percentage' => 9,
                'similar_slugs' => ['boss-bottled', 'dior-sauvage'],
                'is_active' => true,
            ],
            [
                'name' => 'Y Eau de Parfum',
                'slug' => 'y-eau-de-parfum',
                'brand' => 'Yves Saint Laurent',
                'gender' => 'Homme || رجالي',
                'short_description' => 'Aromatique moderne a la pomme, sauge et bois ambrés. || عطري عصري بالتفاح والميرمية والأخشاب العنبرية.',
                'description' => 'Y EDP marie fraicheur fruitee, coeur aromatique et base profonde ambree-boisee. Un parfum contemporain, polyvalent et tres apprecie. || يمزج Y EDP بين انتعاش فاكهي، قلب عطري، وقاعدة عميقة عنبرية خشبية. عطر معاصر ومتعدد الاستعمالات ومحبوب جداً.',
                'price' => 99.00,
                'image_url' => null,
                'country_of_origin' => 'France || فرنسا',
                'size_options' => ['60ml', '100ml', '200ml'],
                'stock_status' => 'En stock || متوفر',
                'fragrance_family' => 'Aromatique fougere || عطري فوجير',
                'recipe' => 'Signature propre et moderne: pomme acidulee, aromates verts, puis ambre boise dense en fond. || توقيع نظيف وعصري: تفاح حامضي، أعشاب خضراء، ثم عنبر خشبي كثيف في القاعدة.',
                'top_notes' => ['Pomme || تفاح', 'Bergamote || برغموت', 'Gingembre || زنجبيل'],
                'heart_notes' => ['Sauge || ميرمية', 'Baies de genièvre || توت العرعر', 'Geranium || إبرة الراعي'],
                'base_notes' => ['Bois ambrés || أخشاب عنبرية', 'Feve tonka || حبوب التونكا', 'Cedre || خشب الأرز', 'Encens || بخور'],
                'longevity' => '8-10 heures || 8-10 ساعات',
                'sillage' => 'Modere a fort || متوسط إلى فواح',
                'vibe' => 'Moderne, net et ambitieux || عصري ونظيف وطموح',
                'when_to_wear' => 'Toute l annee, bureau et sorties || طوال السنة، للمكتب والخروجات',
                'feeling' => 'Motivation et assurance || تحفيز وثقة',
                'average_rating' => 4.7,
                'reviews_count' => 236,
                'reviews' => [
                    ['author' => 'Anas', 'rating' => 5, 'comment' => 'Tres polyvalent et complimenté.', 'date' => '2026-04-04'],
                    ['author' => 'Hicham', 'rating' => 4, 'comment' => 'Bonne tenue, propre et moderne.', 'date' => '2026-03-27'],
                ],
                'bottle_images' => [null],
                'packaging_images' => [null],
                'lifestyle_images' => [null],
                'ingredients' => ['Alcohol Denat.', 'Parfum', 'Limonene', 'Linalool', 'Citral'],
                'delivery_info' => 'Livraison 24-48h partout au Maroc || توصيل خلال 24-48 ساعة في جميع أنحاء المغرب',
                'return_policy' => 'Retour sous 7 jours si le produit est non ouvert || إرجاع خلال 7 أيام إذا كان المنتج غير مفتوح',
                'authenticity_guarantee' => 'Parfum 100% authentique garanti || عطر أصلي 100% مضمون',
                'is_best_seller' => true,
                'is_trending' => true,
                'discount_percentage' => 12,
                'similar_slugs' => ['l-homme-ysl', 'dior-sauvage'],
                'is_active' => true,
            ],
            [
                'name' => 'Sauvage Eau de Parfum',
                'slug' => 'dior-sauvage',
                'brand' => 'Dior',
                'gender' => 'Homme || رجالي',
                'short_description' => 'Fraicheur boisee epicee autour de la bergamote et de l ambroxan. || انتعاش خشبي متبّل حول البرغموت والأمبروكسان.',
                'description' => 'Sauvage EDP est celebre pour son ouverture bergamote-poivre tres lumineuse et sa base ambrée boisee moderne, avec une projection marquee. || يشتهر Sauvage EDP بافتتاحية البرغموت والفلفل المضيئة جداً وقاعدة عنبرية خشبية عصرية مع فوحان واضح.',
                'price' => 108.00,
                'image_url' => null,
                'country_of_origin' => 'France || فرنسا',
                'size_options' => ['60ml', '100ml', '200ml'],
                'stock_status' => 'En stock || متوفر',
                'fragrance_family' => 'Aromatique boise epice || عطري خشبي متبّل',
                'recipe' => 'Construction contrastée: agrume vif, epices seches et fond ambroxan-cedre tres contemporain. || بناء متباين: حمضيات حيوية، توابل جافة، وقاعدة أمبروكسان-أرز معاصرة جداً.',
                'top_notes' => ['Bergamote de Calabre || برغموت كالابريا', 'Poivre || فلفل'],
                'heart_notes' => ['Lavande || لافندر', 'Poivre de Sichuan || فلفل سيشوان', 'Geranium || إبرة الراعي', 'Patchouli || باتشولي'],
                'base_notes' => ['Ambroxan || أمبروكسان', 'Cedre || خشب الأرز', 'Labdanum || لابدانوم'],
                'longevity' => '8-10 heures || 8-10 ساعات',
                'sillage' => 'Fort || فواح',
                'vibe' => 'Puissant, propre et magnetique || قوي ونظيف ومغناطيسي',
                'when_to_wear' => 'Jour et nuit, toute l annee || نهاراً وليلاً طوال السنة',
                'feeling' => 'Presence et impact || حضور وتأثير',
                'average_rating' => 4.8,
                'reviews_count' => 281,
                'reviews' => [
                    ['author' => 'Walid', 'rating' => 5, 'comment' => 'Projection excellente et tres masculine.', 'date' => '2026-04-05'],
                    ['author' => 'Imad', 'rating' => 5, 'comment' => 'Un des meilleurs polyvalents modernes.', 'date' => '2026-03-28'],
                ],
                'bottle_images' => [null],
                'packaging_images' => [null],
                'lifestyle_images' => [null],
                'ingredients' => ['Alcohol Denat.', 'Parfum', 'Limonene', 'Linalool', 'Citral', 'Coumarin'],
                'delivery_info' => 'Livraison 24-48h partout au Maroc || توصيل خلال 24-48 ساعة في جميع أنحاء المغرب',
                'return_policy' => 'Retour sous 7 jours si le produit est non ouvert || إرجاع خلال 7 أيام إذا كان المنتج غير مفتوح',
                'authenticity_guarantee' => 'Parfum 100% authentique garanti || عطر أصلي 100% مضمون',
                'is_best_seller' => true,
                'is_trending' => true,
                'discount_percentage' => 6,
                'similar_slugs' => ['invictus', 'y-eau-de-parfum'],
                'is_active' => true,
            ],
            [
                'name' => 'Acqua Di Gio Eau de Parfum',
                'slug' => 'acqua-di-gio',
                'brand' => 'Giorgio Armani',
                'gender' => 'Homme || رجالي',
                'short_description' => 'Fraicheur marine lumineuse avec agrumes et fond boise propre. || انتعاش بحري مضيء مع حمضيات وقاعدة خشبية نظيفة.',
                'description' => 'Un classique frais et elegant: ouverture hespéridée, coeur aquatique-aromatique et base boisee musquee facile a porter tous les jours. || كلاسيكي منعش وأنيق: بداية حمضية، قلب مائي عطري، وقاعدة خشبية مسكية سهلة الارتداء يومياً.',
                'price' => 97.00,
                'image_url' => null,
                'country_of_origin' => 'Italie || إيطاليا',
                'size_options' => ['50ml', '100ml', '200ml'],
                'stock_status' => 'En stock || متوفر',
                'fragrance_family' => 'Aquatique aromatique || مائي عطري',
                'recipe' => 'Accord marin-citronne avec un coeur herbacé et une base cedre-musc. || تركيبة بحرية حمضية مع قلب عشبي وقاعدة أرز-مسك.',
                'top_notes' => ['Bergamote || برغموت', 'Citron vert || ليمون أخضر', 'Mandarine || يوسفي'],
                'heart_notes' => ['Notes marines || نغمات بحرية', 'Jasmin || ياسمين', 'Romarin || إكليل الجبل'],
                'base_notes' => ['Cedre || خشب الأرز', 'Musc blanc || مسك أبيض', 'Patchouli || باتشولي'],
                'longevity' => '6-8 heures || 6-8 ساعات',
                'sillage' => 'Modere || متوسط',
                'vibe' => 'Frais, propre et raffine || منعش ونظيف وراقٍ',
                'when_to_wear' => 'Printemps-ete et usage quotidien || الربيع والصيف والاستخدام اليومي',
                'feeling' => 'Fraicheur elegante || انتعاش أنيق',
                'average_rating' => 4.6,
                'reviews_count' => 198,
                'reviews' => [
                    ['author' => 'Sami', 'rating' => 5, 'comment' => 'Tres frais pour la journee.', 'date' => '2026-04-05'],
                    ['author' => 'Bilal', 'rating' => 4, 'comment' => 'Parfait pour le printemps.', 'date' => '2026-03-29'],
                ],
                'bottle_images' => [null],
                'packaging_images' => [null],
                'lifestyle_images' => [null],
                'ingredients' => ['Alcohol Denat.', 'Parfum', 'Limonene', 'Linalool', 'Citral'],
                'delivery_info' => 'Livraison 24-48h partout au Maroc || توصيل خلال 24-48 ساعة في جميع أنحاء المغرب',
                'return_policy' => 'Retour sous 7 jours si le produit est non ouvert || إرجاع خلال 7 أيام إذا كان المنتج غير مفتوح',
                'authenticity_guarantee' => 'Parfum 100% authentique garanti || عطر أصلي 100% مضمون',
                'is_best_seller' => true,
                'is_trending' => true,
                'discount_percentage' => 9,
                'similar_slugs' => ['invictus', 'dior-sauvage'],
                'is_active' => true,
            ],
            [
                'name' => 'Blue Seduction Eau de Parfum',
                'slug' => 'blue-seduction',
                'brand' => 'Antonio Banderas',
                'gender' => 'Homme || رجالي',
                'short_description' => 'Fraicheur aromatique fruitee avec menthe et accord aquatique. || انتعاش عطري فاكهي مع نعناع ولمسة مائية.',
                'description' => 'Blue Seduction offre un style frais, jeune et facile: notes fruitees aquatiques en tete, coeur aromatique, puis un fond musque leger. || يقدم Blue Seduction أسلوباً منعشاً وشبابياً وسهل الاستخدام: مقدمة فاكهية مائية، قلب عطري، ثم قاعدة مسكية خفيفة.',
                'price' => 79.00,
                'image_url' => null,
                'country_of_origin' => 'Espagne || إسبانيا',
                'size_options' => ['50ml', '100ml', '200ml'],
                'stock_status' => 'En stock || متوفر',
                'fragrance_family' => 'Aromatique aquatique || عطري مائي',
                'recipe' => 'Ouverture melon-bergamote, coeur menthe-cardamome, et fond boise musque leger. || افتتاحية شمام وبرغموت، قلب نعناع وهيل، وقاعدة خشبية مسكية خفيفة.',
                'top_notes' => ['Melon || شمام', 'Bergamote || برغموت', 'Cassis || كشمش أسود'],
                'heart_notes' => ['Menthe || نعناع', 'Cardamome || هيل', 'Noix de muscade || جوزة الطيب'],
                'base_notes' => ['Musc || مسك', 'Cedre || خشب الأرز', 'Ambre || عنبر'],
                'longevity' => '5-7 heures || 5-7 ساعات',
                'sillage' => 'Modere || متوسط',
                'vibe' => 'Jeune, propre et decontracte || شبابي ونظيف ومريح',
                'when_to_wear' => 'Journee, printemps-ete || النهار، الربيع والصيف',
                'feeling' => 'Fraicheur et bonne humeur || انتعاش ومزاج جيد',
                'average_rating' => 4.3,
                'reviews_count' => 143,
                'reviews' => [
                    ['author' => 'Yassine', 'rating' => 4, 'comment' => 'Super rapport qualite prix.', 'date' => '2026-04-02'],
                    ['author' => 'Hamza', 'rating' => 4, 'comment' => 'Tres agreable en ete.', 'date' => '2026-03-22'],
                ],
                'bottle_images' => [null],
                'packaging_images' => [null],
                'lifestyle_images' => [null],
                'ingredients' => ['Alcohol Denat.', 'Parfum', 'Limonene', 'Linalool', 'Citral'],
                'delivery_info' => 'Livraison 24-48h partout au Maroc || توصيل خلال 24-48 ساعة في جميع أنحاء المغرب',
                'return_policy' => 'Retour sous 7 jours si le produit est non ouvert || إرجاع خلال 7 أيام إذا كان المنتج غير مفتوح',
                'authenticity_guarantee' => 'Parfum 100% authentique garanti || عطر أصلي 100% مضمون',
                'is_best_seller' => false,
                'is_trending' => true,
                'discount_percentage' => 11,
                'similar_slugs' => ['acqua-di-gio', 'invictus'],
                'is_active' => true,
            ],
            [
                'name' => 'Erba Pura Eau de Parfum',
                'slug' => 'erba-pura',
                'brand' => 'Xerjoff',
                'gender' => 'Unisex || للجنسين',
                'short_description' => 'Fruite intense avec musc blanc et ambre doux. || فاكهي قوي مع مسك أبيض وعنبر ناعم.',
                'description' => 'Erba Pura est un parfum fruité-luxueux: ouverture d agrumes et fruits exotiques, coeur veloute, puis fond musc-ambre tres enveloppant. || Erba Pura عطر فاخر فاكهي: بداية حمضيات وفواكه استوائية، قلب ناعم، ثم قاعدة مسك وعنبر غامرة.',
                'price' => 149.00,
                'image_url' => null,
                'country_of_origin' => 'Italie || إيطاليا',
                'size_options' => ['50ml', '100ml'],
                'stock_status' => 'En stock || متوفر',
                'fragrance_family' => 'Fruite ambre musque || فاكهي عنبري مسكي',
                'recipe' => 'Accord fruits mediterraneens et agrumes sur un fond musc blanc et ambre. || مزيج فواكه متوسطية وحمضيات فوق قاعدة مسك أبيض وعنبر.',
                'top_notes' => ['Orange || برتقال', 'Bergamote || برغموت', 'Citron || ليمون'],
                'heart_notes' => ['Fruits exotiques || فواكه استوائية'],
                'base_notes' => ['Musc blanc || مسك أبيض', 'Ambre || عنبر', 'Vanille || فانيلا'],
                'longevity' => '8-10 heures || 8-10 ساعات',
                'sillage' => 'Fort || فواح',
                'vibe' => 'Luxueux et seduisant || فاخر وجذاب',
                'when_to_wear' => 'Soiree et occasions speciales || المساء والمناسبات الخاصة',
                'feeling' => 'Opulence et elegance || فخامة وأناقة',
                'average_rating' => 4.7,
                'reviews_count' => 121,
                'reviews' => [
                    ['author' => 'Nour', 'rating' => 5, 'comment' => 'Sillage incroyable, tres chic.', 'date' => '2026-04-08'],
                    ['author' => 'Yassin', 'rating' => 4, 'comment' => 'Fruite et tres longue tenue.', 'date' => '2026-03-31'],
                ],
                'bottle_images' => [null],
                'packaging_images' => [null],
                'lifestyle_images' => [null],
                'ingredients' => ['Alcohol Denat.', 'Parfum', 'Limonene', 'Linalool', 'Citral'],
                'delivery_info' => 'Livraison 24-48h partout au Maroc || توصيل خلال 24-48 ساعة في جميع أنحاء المغرب',
                'return_policy' => 'Retour sous 7 jours si le produit est non ouvert || إرجاع خلال 7 أيام إذا كان المنتج غير مفتوح',
                'authenticity_guarantee' => 'Parfum 100% authentique garanti || عطر أصلي 100% مضمون',
                'is_best_seller' => true,
                'is_trending' => true,
                'discount_percentage' => 5,
                'similar_slugs' => ['versace-eros', 'imagination'],
                'is_active' => true,
            ],
            [
                'name' => 'Imagination Eau de Parfum',
                'slug' => 'imagination',
                'brand' => 'Louis Vuitton',
                'gender' => 'Homme || رجالي',
                'short_description' => 'Aromatique citronne et propre avec the noir. || عطري حمضي نظيف مع شاي أسود.',
                'description' => 'Imagination propose une elegance moderne: agrumes lumineux, coeur the noir-gingembre, puis fond boise ambre subtil. || يقدم Imagination أناقة عصرية: حمضيات مضيئة، قلب شاي أسود وزنجبيل، ثم قاعدة خشبية عنبرية ناعمة.',
                'price' => 159.00,
                'image_url' => null,
                'country_of_origin' => 'France || فرنسا',
                'size_options' => ['50ml', '100ml'],
                'stock_status' => 'En stock || متوفر',
                'fragrance_family' => 'Aromatique citrus boise || عطري حمضي خشبي',
                'recipe' => 'Accord bergamote-citron, coeur the noir et gingembre, base cedre-ambre. || مزيج برغموت-ليمون، قلب شاي أسود وزنجبيل، وقاعدة أرز-عنبر.',
                'top_notes' => ['Bergamote || برغموت', 'Citron || ليمون', 'Neroli || نيرولي'],
                'heart_notes' => ['The noir || شاي أسود', 'Gingembre || زنجبيل', 'Cannelle || قرفة'],
                'base_notes' => ['Cedre || خشب الأرز', 'Ambre || عنبر', 'Encens || بخور'],
                'longevity' => '7-9 heures || 7-9 ساعات',
                'sillage' => 'Modere a fort || متوسط إلى فواح',
                'vibe' => 'Moderne et raffine || عصري وراقٍ',
                'when_to_wear' => 'Jour et soiree || النهار والمساء',
                'feeling' => 'Confiance elegante || ثقة أنيقة',
                'average_rating' => 4.8,
                'reviews_count' => 98,
                'reviews' => [
                    ['author' => 'Hamid', 'rating' => 5, 'comment' => 'Tres propre, tres classe.', 'date' => '2026-04-07'],
                    ['author' => 'Zakaria', 'rating' => 4, 'comment' => 'Belle note de the noir.', 'date' => '2026-03-30'],
                ],
                'bottle_images' => [null],
                'packaging_images' => [null],
                'lifestyle_images' => [null],
                'ingredients' => ['Alcohol Denat.', 'Parfum', 'Limonene', 'Linalool', 'Citral'],
                'delivery_info' => 'Livraison 24-48h partout au Maroc || توصيل خلال 24-48 ساعة في جميع أنحاء المغرب',
                'return_policy' => 'Retour sous 7 jours si le produit est non ouvert || إرجاع خلال 7 أيام إذا كان المنتج غير مفتوح',
                'authenticity_guarantee' => 'Parfum 100% authentique garanti || عطر أصلي 100% مضمون',
                'is_best_seller' => false,
                'is_trending' => true,
                'discount_percentage' => 4,
                'similar_slugs' => ['y-eau-de-parfum', 'erba-pura'],
                'is_active' => true,
            ],
            [
                'name' => 'Light Blue Eau de Parfum',
                'slug' => 'dolce-gabbana-light-blue',
                'brand' => 'Dolce & Gabbana',
                'gender' => 'Homme || رجالي',
                'short_description' => 'Fraicheur mediterraneenne aux agrumes et cedre. || انتعاش متوسطي بحمضيات وأرز.',
                'description' => 'Light Blue est un parfum frais et energique: ouverture citronnee, coeur aromatique, base bois-muscs legere et propre. || Light Blue عطر منعش وحيوي: افتتاحية ليمونية، قلب عطري، وقاعدة خشبية مسكية خفيفة ونظيفة.',
                'price' => 89.00,
                'image_url' => null,
                'country_of_origin' => 'Italie || إيطاليا',
                'size_options' => ['50ml', '100ml', '200ml'],
                'stock_status' => 'En stock || متوفر',
                'fragrance_family' => 'Citrus aromatique || حمضي عطري',
                'recipe' => 'Citron et pamplemousse en tete, aromates marins au coeur, fond cedre-musc. || ليمون وجريب فروت في المقدمة، أعشاب مائية في القلب، وقاعدة أرز-مسك.',
                'top_notes' => ['Citron de Sicile || ليمون صقلي', 'Pamplemousse || جريب فروت', 'Bergamote || برغموت'],
                'heart_notes' => ['Romarin || إكليل الجبل', 'Poivre || فلفل', 'Bois de rose || خشب الورد'],
                'base_notes' => ['Musc || مسك', 'Encens || بخور', 'Cedre || خشب الأرز'],
                'longevity' => '5-7 heures || 5-7 ساعات',
                'sillage' => 'Modere || متوسط',
                'vibe' => 'Frais et dynamique || منعش وحيوي',
                'when_to_wear' => 'Printemps-ete, journee || الربيع والصيف، النهار',
                'feeling' => 'Fraicheur et energie || انتعاش وطاقة',
                'average_rating' => 4.4,
                'reviews_count' => 133,
                'reviews' => [
                    ['author' => 'Adil', 'rating' => 4, 'comment' => 'Top pour la chaleur.', 'date' => '2026-04-06'],
                    ['author' => 'Nabil', 'rating' => 4, 'comment' => 'Frais et facile a porter.', 'date' => '2026-03-19'],
                ],
                'bottle_images' => [null],
                'packaging_images' => [null],
                'lifestyle_images' => [null],
                'ingredients' => ['Alcohol Denat.', 'Parfum', 'Limonene', 'Linalool', 'Citral'],
                'delivery_info' => 'Livraison 24-48h partout au Maroc || توصيل خلال 24-48 ساعة في جميع أنحاء المغرب',
                'return_policy' => 'Retour sous 7 jours si le produit est non ouvert || إرجاع خلال 7 أيام إذا كان المنتج غير مفتوح',
                'authenticity_guarantee' => 'Parfum 100% authentique garanti || عطر أصلي 100% مضمون',
                'is_best_seller' => false,
                'is_trending' => true,
                'discount_percentage' => 8,
                'similar_slugs' => ['acqua-di-gio', 'blue-seduction'],
                'is_active' => true,
            ],
            [
                'name' => 'Versace Eros Eau de Parfum',
                'slug' => 'versace-eros',
                'brand' => 'Versace',
                'gender' => 'Homme || رجالي',
                'short_description' => 'Aromatique oriental a la menthe et vanille. || عطري شرقي بالنعناع والفانيلا.',
                'description' => 'Eros combine fraicheur de menthe et pomme verte avec un fond chaud vanille-tonka-cedre pour un style seduisant. || يجمع Eros بين انتعاش النعناع والتفاح الأخضر مع قاعدة دافئة من الفانيلا والتونكا والأرز لأسلوب جذاب.',
                'price' => 105.00,
                'image_url' => null,
                'country_of_origin' => 'Italie || إيطاليا',
                'size_options' => ['50ml', '100ml', '200ml'],
                'stock_status' => 'En stock || متوفر',
                'fragrance_family' => 'Oriental aromatique || شرقي عطري',
                'recipe' => 'Menthe-citron en tete, geranium et pomme en coeur, fond vanille-tonka-cedre. || نعناع-ليمون في المقدمة، إبرة الراعي وتفاح في القلب، وقاعدة فانيلا-تونكا-أرز.',
                'top_notes' => ['Menthe || نعناع', 'Citron || ليمون', 'Pomme verte || تفاح أخضر'],
                'heart_notes' => ['Geranium || إبرة الراعي', 'Ambroxan || أمبروكسان'],
                'base_notes' => ['Vanille || فانيلا', 'Feve tonka || حبوب التونكا', 'Cedre || خشب الأرز', 'Vetiver || فيتيفر'],
                'longevity' => '8-10 heures || 8-10 ساعات',
                'sillage' => 'Fort || فواح',
                'vibe' => 'Seduisant et energique || جذاب وحيوي',
                'when_to_wear' => 'Soiree et sorties || المساء والخروجات',
                'feeling' => 'Charisme et puissance || كاريزما وقوة',
                'average_rating' => 4.7,
                'reviews_count' => 207,
                'reviews' => [
                    ['author' => 'Badr', 'rating' => 5, 'comment' => 'Projection tres forte.', 'date' => '2026-04-09'],
                    ['author' => 'Reda', 'rating' => 4, 'comment' => 'Excellent pour la nuit.', 'date' => '2026-03-26'],
                ],
                'bottle_images' => [null],
                'packaging_images' => [null],
                'lifestyle_images' => [null],
                'ingredients' => ['Alcohol Denat.', 'Parfum', 'Limonene', 'Linalool', 'Coumarin'],
                'delivery_info' => 'Livraison 24-48h partout au Maroc || توصيل خلال 24-48 ساعة في جميع أنحاء المغرب',
                'return_policy' => 'Retour sous 7 jours si le produit est non ouvert || إرجاع خلال 7 أيام إذا كان المنتج غير مفتوح',
                'authenticity_guarantee' => 'Parfum 100% authentique garanti || عطر أصلي 100% مضمون',
                'is_best_seller' => true,
                'is_trending' => true,
                'discount_percentage' => 7,
                'similar_slugs' => ['dior-sauvage', 'erba-pura'],
                'is_active' => true,
            ],
        ];

        $activeSlugs = array_column($perfumes, 'slug');

        Perfume::query()->whereNotIn('slug', $activeSlugs)->whereDoesntHave('orders')->delete();
        Perfume::query()->whereNotIn('slug', $activeSlugs)->update(['is_active' => false]);

        foreach ($perfumes as $perfume) {
            Perfume::updateOrCreate(['slug' => $perfume['slug']], $perfume);
        }
    }
}
