<?php

namespace Database\Seeders;

use App\Models\Perfume;
use Illuminate\Database\Seeder;

class PerfumeSeeder extends Seeder
{
    public function run(): void
    {
        $perfumes = [
            [
                'name' => 'L Homme',
                'slug' => 'l-homme-ysl',
                'brand' => 'Yves Saint Laurent',
                'gender' => 'Homme || رجالي',
                'short_description' => 'Boise aromatique raffine. || خشبي عطري راقٍ.',
                'description' => 'Un style chic et urbain, propre et moderne. || أسلوب أنيق وحضري، نظيف وعصري.',
                'price' => 69.00,
                'image_url' => null,
                'country_of_origin' => 'France || فرنسا',
                'size_options' => ['20ml', '30ml', '50ml'],
                'stock_status' => 'En stock || متوفر',
                'fragrance_family' => 'Boise aromatique || خشبي عطري',
                'recipe' => 'Agrumes, aromates, fond boise doux. || حمضيات وأعشاب وقاعدة خشبية ناعمة.',
                'top_notes' => ['Gingembre || زنجبيل', 'Bergamote || برغموت', 'Citron || ليمون'],
                'heart_notes' => ['Basilic || ريحان', 'Poivre blanc || فلفل أبيض', 'Feuille de violette || ورق البنفسج'],
                'base_notes' => ['Feve tonka || حبوب التونكا', 'Cedre || خشب الأرز', 'Vetiver || فيتيفر'],
                'longevity' => '6-8 heures || 6-8 ساعات',
                'sillage' => 'Modere || متوسط',
                'vibe' => 'Chic et moderne || أنيق وعصري',
                'when_to_wear' => 'Quotidien || يومي',
                'feeling' => 'Elegance || أناقة',
                'average_rating' => 4.6,
                'reviews_count' => 120,
                'reviews' => [],
                'bottle_images' => [null],
                'packaging_images' => [null],
                'lifestyle_images' => [null],
                'ingredients' => [
                    'Gingembre || زنجبيل',
                    'Bergamote || برغموت',
                    'Citron || ليمون',
                    'Basilic || ريحان',
                    'Poivre blanc || فلفل أبيض',
                    'Feuille de violette || ورق البنفسج',
                    'Feve tonka || حبوب التونكا',
                    'Cedre || خشب الأرز',
                    'Vetiver || فيتيفر',
                ],
                'delivery_info' => 'Livraison gratuite || توصيل مجاني',
                'return_policy' => 'Retour sous 7 jours si non ouvert || إرجاع خلال 7 أيام إذا كان المنتج غير مفتوح',
                'authenticity_guarantee' => 'Parfum 100% authentique garanti || عطر أصلي 100% مضمون',
                'is_best_seller' => true,
                'is_trending' => true,
                'discount_percentage' => 0,
                'similar_slugs' => ['bleu-chanel', 'y-eau-de-parfum'],
                'is_active' => true,
            ],
            [
                'name' => 'Light Bleu',
                'slug' => 'dolce-gabbana-light-blue',
                'brand' => 'Dolce & Gabbana',
                'gender' => 'Homme || رجالي',
                'short_description' => 'Frais mediterraneen aux agrumes. || انتعاش متوسطي بالحمضيات.',
                'description' => 'Un parfum frais, lumineux et energique. || عطر منعش ومشرق وحيوي.',
                'price' => 69.00,
                'image_url' => null,
                'country_of_origin' => 'Italie || إيطاليا',
                'size_options' => ['20ml', '30ml', '50ml'],
                'stock_status' => 'En stock || متوفر',
                'fragrance_family' => 'Citrus aromatique || حمضي عطري',
                'recipe' => 'Agrumes frais et base musquee propre. || حمضيات منعشة وقاعدة مسكية نظيفة.',
                'top_notes' => ['Pamplemousse || جريب فروت', 'Bergamote || برغموت', 'Mandarine || يوسفي'],
                'heart_notes' => ['Notes marines || نغمات بحرية', 'Genievre || العرعر', 'Romarin || إكليل الجبل'],
                'base_notes' => ['Musc || مسك', 'Encens || بخور', 'Mousse de chene || طحلب البلوط'],
                'longevity' => '5-7 heures || 5-7 ساعات',
                'sillage' => 'Modere || متوسط',
                'vibe' => 'Frais et dynamique || منعش وحيوي',
                'when_to_wear' => 'Journee || النهار',
                'feeling' => 'Fraicheur || انتعاش',
                'average_rating' => 4.5,
                'reviews_count' => 110,
                'reviews' => [],
                'bottle_images' => [null],
                'packaging_images' => [null],
                'lifestyle_images' => [null],
                'ingredients' => [
                    'Pamplemousse || جريب فروت',
                    'Bergamote || برغموت',
                    'Mandarine || يوسفي',
                    'Notes marines || نغمات بحرية',
                    'Genievre || العرعر',
                    'Romarin || إكليل الجبل',
                    'Musc || مسك',
                    'Encens || بخور',
                    'Mousse de chene || طحلب البلوط',
                ],
                'delivery_info' => 'Livraison gratuite || توصيل مجاني',
                'return_policy' => 'Retour sous 7 jours si non ouvert || إرجاع خلال 7 أيام إذا كان المنتج غير مفتوح',
                'authenticity_guarantee' => 'Parfum 100% authentique garanti || عطر أصلي 100% مضمون',
                'is_best_seller' => true,
                'is_trending' => true,
                'discount_percentage' => 0,
                'similar_slugs' => ['acqua-di-gio', 'bleu-chanel'],
                'is_active' => true,
            ],
            [
                'name' => 'Y',
                'slug' => 'y-eau-de-parfum',
                'brand' => 'Yves Saint Laurent',
                'gender' => 'Homme || رجالي',
                'short_description' => 'Aromatique moderne et propre. || عطري عصري ونظيف.',
                'description' => 'Frais, moderne et polyvalent pour tous les jours. || منعش وعصري ومتعدد الاستعمالات يوميا.',
                'price' => 69.00,
                'image_url' => null,
                'country_of_origin' => 'France || فرنسا',
                'size_options' => ['20ml', '30ml', '50ml'],
                'stock_status' => 'En stock || متوفر',
                'fragrance_family' => 'Aromatique fougere || عطري فوجير',
                'recipe' => 'Fruite frais et bois ambre. || فاكهي منعش مع أخشاب عنبرية.',
                'top_notes' => ['Pomme || تفاح', 'Bergamote || برغموت', 'Gingembre || زنجبيل'],
                'heart_notes' => ['Sauge || ميرمية', 'Geranium || إبرة الراعي', 'Baies de genièvre || توت العرعر'],
                'base_notes' => ['Bois ambres || أخشاب عنبرية', 'Feve tonka || حبوب التونكا', 'Cedre || خشب الأرز'],
                'longevity' => '7-9 heures || 7-9 ساعات',
                'sillage' => 'Modere || متوسط',
                'vibe' => 'Moderne et net || عصري ونظيف',
                'when_to_wear' => 'Toute l annee || طوال السنة',
                'feeling' => 'Confiance || ثقة',
                'average_rating' => 4.7,
                'reviews_count' => 140,
                'reviews' => [],
                'bottle_images' => [null],
                'packaging_images' => [null],
                'lifestyle_images' => [null],
                'ingredients' => [
                    'Pomme || تفاح',
                    'Bergamote || برغموت',
                    'Gingembre || زنجبيل',
                    'Sauge || ميرمية',
                    'Geranium || إبرة الراعي',
                    'Baies de genièvre || توت العرعر',
                    'Bois ambres || أخشاب عنبرية',
                    'Feve tonka || حبوب التونكا',
                    'Cedre || خشب الأرز',
                ],
                'delivery_info' => 'Livraison gratuite || توصيل مجاني',
                'return_policy' => 'Retour sous 7 jours si non ouvert || إرجاع خلال 7 أيام إذا كان المنتج غير مفتوح',
                'authenticity_guarantee' => 'Parfum 100% authentique garanti || عطر أصلي 100% مضمون',
                'is_best_seller' => true,
                'is_trending' => true,
                'discount_percentage' => 0,
                'similar_slugs' => ['l-homme-ysl', 'bleu-chanel'],
                'is_active' => true,
            ],
            [
                'name' => 'Bleu Chanel',
                'slug' => 'bleu-chanel',
                'brand' => 'Chanel',
                'gender' => 'Homme || رجالي',
                'short_description' => 'Boise aromatique profond. || خشبي عطري عميق.',
                'description' => 'Elegant, frais et boise avec une tenue durable. || أنيق ومنعش وخشبي مع ثبات جيد.',
                'price' => 69.00,
                'image_url' => null,
                'country_of_origin' => 'France || فرنسا',
                'size_options' => ['20ml', '30ml', '50ml'],
                'stock_status' => 'En stock || متوفر',
                'fragrance_family' => 'Boise aromatique || خشبي عطري',
                'recipe' => 'Agrumes en tete, coeur aromatique, fond boise. || حمضيات في المقدمة، قلب عطري، قاعدة خشبية.',
                'top_notes' => ['Pamplemousse || جريب فروت', 'Citron || ليمون', 'Menthe || نعناع'],
                'heart_notes' => ['Gingembre || زنجبيل', 'Noix de muscade || جوزة الطيب', 'Jasmin || ياسمين'],
                'base_notes' => ['Encens || بخور', 'Vetiver || فيتيفر', 'Cedre || خشب الأرز'],
                'longevity' => '7-9 heures || 7-9 ساعات',
                'sillage' => 'Modere || متوسط',
                'vibe' => 'Elegance classique || أناقة كلاسيكية',
                'when_to_wear' => 'Jour et nuit || نهاراً وليلاً',
                'feeling' => 'Charisme || كاريزما',
                'average_rating' => 4.6,
                'reviews_count' => 130,
                'reviews' => [],
                'bottle_images' => [null],
                'packaging_images' => [null],
                'lifestyle_images' => [null],
                'ingredients' => [
                    'Pamplemousse || جريب فروت',
                    'Citron || ليمون',
                    'Menthe || نعناع',
                    'Gingembre || زنجبيل',
                    'Noix de muscade || جوزة الطيب',
                    'Jasmin || ياسمين',
                    'Encens || بخور',
                    'Vetiver || فيتيفر',
                    'Cedre || خشب الأرز',
                ],
                'delivery_info' => 'Livraison gratuite || توصيل مجاني',
                'return_policy' => 'Retour sous 7 jours si non ouvert || إرجاع خلال 7 أيام إذا كان المنتج غير مفتوح',
                'authenticity_guarantee' => 'Parfum 100% authentique garanti || عطر أصلي 100% مضمون',
                'is_best_seller' => true,
                'is_trending' => true,
                'discount_percentage' => 0,
                'similar_slugs' => ['l-homme-ysl', 'y-eau-de-parfum'],
                'is_active' => true,
            ],
            [
                'name' => 'Sauvage',
                'slug' => 'dior-sauvage',
                'brand' => 'Dior',
                'gender' => 'Homme || رجالي',
                'short_description' => 'Fraicheur boisee epicee. || انتعاش خشبي متبّل.',
                'description' => 'Puissant, propre et magnetique. || قوي ونظيف ومغناطيسي.',
                'price' => 69.00,
                'image_url' => null,
                'country_of_origin' => 'France || فرنسا',
                'size_options' => ['20ml', '30ml', '50ml'],
                'stock_status' => 'En stock || متوفر',
                'fragrance_family' => 'Aromatique boise || عطري خشبي',
                'recipe' => 'Bergamote, epices, fond boise ambre. || برغموت وتوابل وقاعدة خشبية عنبرية.',
                'top_notes' => ['Bergamote || برغموت'],
                'heart_notes' => ['Poivre de Sichuan || فلفل سيشوان', 'Lavande || لافندر'],
                'base_notes' => ['Ambroxan || أمبروكسان', 'Vanille || فانيلا', 'Labdanum || لابدانوم'],
                'longevity' => '8-10 heures || 8-10 ساعات',
                'sillage' => 'Fort || فواح',
                'vibe' => 'Puissant et propre || قوي ونظيف',
                'when_to_wear' => 'Toute l annee || طوال السنة',
                'feeling' => 'Impact || تأثير',
                'average_rating' => 4.8,
                'reviews_count' => 160,
                'reviews' => [],
                'bottle_images' => [null],
                'packaging_images' => [null],
                'lifestyle_images' => [null],
                'ingredients' => [
                    'Bergamote || برغموت',
                    'Poivre de Sichuan || فلفل سيشوان',
                    'Lavande || لافندر',
                    'Ambroxan || أمبروكسان',
                    'Vanille || فانيلا',
                    'Labdanum || لابدانوم',
                ],
                'delivery_info' => 'Livraison gratuite || توصيل مجاني',
                'return_policy' => 'Retour sous 7 jours si non ouvert || إرجاع خلال 7 أيام إذا كان المنتج غير مفتوح',
                'authenticity_guarantee' => 'Parfum 100% authentique garanti || عطر أصلي 100% مضمون',
                'is_best_seller' => true,
                'is_trending' => true,
                'discount_percentage' => 0,
                'similar_slugs' => ['invictus', 'versace-eros'],
                'is_active' => true,
            ],
            [
                'name' => 'Stronger With You',
                'slug' => 'stronger-with-you',
                'brand' => 'Emporio Armani',
                'gender' => 'Homme || رجالي',
                'short_description' => 'Oriental doux et chaleureux. || شرقي دافئ وناعم.',
                'description' => 'Chaleureux et seduisant avec vanille et ambre. || دافئ وجذاب مع فانيلا وعنبر.',
                'price' => 69.00,
                'image_url' => null,
                'country_of_origin' => 'Italie || إيطاليا',
                'size_options' => ['20ml', '30ml', '50ml'],
                'stock_status' => 'En stock || متوفر',
                'fragrance_family' => 'Oriental fougere || شرقي فوجير',
                'recipe' => 'Epices douces et base vanille ambree. || توابل ناعمة وقاعدة فانيلا عنبرية.',
                'top_notes' => ['Poivre rose || فلفل وردي', 'Cardamome || هيل', 'Feuille de violette || ورق البنفسج'],
                'heart_notes' => ['Sauge || ميرمية', 'Chataigne || كستناء'],
                'base_notes' => ['Vanille || فانيلا', 'Ambre || عنبر', 'Feve tonka || حبوب التونكا'],
                'longevity' => '7-9 heures || 7-9 ساعات',
                'sillage' => 'Modere || متوسط',
                'vibe' => 'Chaleureux || دافئ',
                'when_to_wear' => 'Soiree || المساء',
                'feeling' => 'Confort || راحة',
                'average_rating' => 4.6,
                'reviews_count' => 125,
                'reviews' => [],
                'bottle_images' => [null],
                'packaging_images' => [null],
                'lifestyle_images' => [null],
                'ingredients' => [
                    'Poivre rose || فلفل وردي',
                    'Cardamome || هيل',
                    'Feuille de violette || ورق البنفسج',
                    'Sauge || ميرمية',
                    'Chataigne || كستناء',
                    'Vanille || فانيلا',
                    'Ambre || عنبر',
                    'Feve tonka || حبوب التونكا',
                ],
                'delivery_info' => 'Livraison gratuite || توصيل مجاني',
                'return_policy' => 'Retour sous 7 jours si non ouvert || إرجاع خلال 7 أيام إذا كان المنتج غير مفتوح',
                'authenticity_guarantee' => 'Parfum 100% authentique garanti || عطر أصلي 100% مضمون',
                'is_best_seller' => true,
                'is_trending' => true,
                'discount_percentage' => 0,
                'similar_slugs' => ['boss-bottled', 'azzaro-wanted'],
                'is_active' => true,
            ],
            [
                'name' => 'Boss Bottled',
                'slug' => 'boss-bottled',
                'brand' => 'Hugo Boss',
                'gender' => 'Homme || رجالي',
                'short_description' => 'Boise epice avec pomme. || خشبي متبّل مع التفاح.',
                'description' => 'Classique boise-epice, elegant et quotidien. || كلاسيكي خشبي متبّل وأنيق يوميا.',
                'price' => 69.00,
                'image_url' => null,
                'country_of_origin' => 'Allemagne || ألمانيا',
                'size_options' => ['20ml', '30ml', '50ml'],
                'stock_status' => 'En stock || متوفر',
                'fragrance_family' => 'Boise epice || خشبي متبّل',
                'recipe' => 'Pomme, cannelle, vanille. || تفاح وقرفة وفانيلا.',
                'top_notes' => ['Pomme || تفاح', 'Bergamote || برغموت', 'Citron || ليمون'],
                'heart_notes' => ['Cannelle || قرفة', 'Geranium || إبرة الراعي', 'Clou de girofle || قرنفل'],
                'base_notes' => ['Vanille || فانيلا', 'Santal || خشب الصندل', 'Cedre || خشب الأرز', 'Vetiver || فيتيفر'],
                'longevity' => '6-8 heures || 6-8 ساعات',
                'sillage' => 'Modere || متوسط',
                'vibe' => 'Chaleureux || دافئ',
                'when_to_wear' => 'Quotidien || يومي',
                'feeling' => 'Confiance || ثقة',
                'average_rating' => 4.6,
                'reviews_count' => 150,
                'reviews' => [],
                'bottle_images' => [null],
                'packaging_images' => [null],
                'lifestyle_images' => [null],
                'ingredients' => [
                    'Pomme || تفاح',
                    'Bergamote || برغموت',
                    'Citron || ليمون',
                    'Cannelle || قرفة',
                    'Geranium || إبرة الراعي',
                    'Clou de girofle || قرنفل',
                    'Vanille || فانيلا',
                    'Santal || خشب الصندل',
                    'Cedre || خشب الأرز',
                    'Vetiver || فيتيفر',
                ],
                'delivery_info' => 'Livraison gratuite || توصيل مجاني',
                'return_policy' => 'Retour sous 7 jours si non ouvert || إرجاع خلال 7 أيام إذا كان المنتج غير مفتوح',
                'authenticity_guarantee' => 'Parfum 100% authentique garanti || عطر أصلي 100% مضمون',
                'is_best_seller' => true,
                'is_trending' => true,
                'discount_percentage' => 0,
                'similar_slugs' => ['azzaro-wanted', 'invictus'],
                'is_active' => true,
            ],
            [
                'name' => 'Acqua Di Gio',
                'slug' => 'acqua-di-gio',
                'brand' => 'Giorgio Armani',
                'gender' => 'Homme || رجالي',
                'short_description' => 'Frais marin et propre. || منعش بحري ونظيف.',
                'description' => 'Un classique frais pour la journee. || كلاسيكي منعش للنهار.',
                'price' => 69.00,
                'image_url' => null,
                'country_of_origin' => 'Italie || إيطاليا',
                'size_options' => ['20ml', '30ml', '50ml'],
                'stock_status' => 'En stock || متوفر',
                'fragrance_family' => 'Aquatique aromatique || مائي عطري',
                'recipe' => 'Agrumes et notes marines propres. || حمضيات ونغمات بحرية نظيفة.',
                'top_notes' => ['Bergamote || برغموت', 'Mandarine verte || يوسفي أخضر', 'Neroli || نيرولي'],
                'heart_notes' => ['Notes marines || نغمات بحرية', 'Jasmin || ياسمين', 'Romarin || إكليل الجبل'],
                'base_notes' => ['Patchouli || باتشولي', 'Cedre || خشب الأرز', 'Musc blanc || مسك أبيض'],
                'longevity' => '6-8 heures || 6-8 ساعات',
                'sillage' => 'Modere || متوسط',
                'vibe' => 'Frais et propre || منعش ونظيف',
                'when_to_wear' => 'Printemps-ete || الربيع والصيف',
                'feeling' => 'Fraicheur || انتعاش',
                'average_rating' => 4.5,
                'reviews_count' => 145,
                'reviews' => [],
                'bottle_images' => [null],
                'packaging_images' => [null],
                'lifestyle_images' => [null],
                'ingredients' => [
                    'Bergamote || برغموت',
                    'Mandarine verte || يوسفي أخضر',
                    'Neroli || نيرولي',
                    'Notes marines || نغمات بحرية',
                    'Jasmin || ياسمين',
                    'Romarin || إكليل الجبل',
                    'Patchouli || باتشولي',
                    'Cedre || خشب الأرز',
                    'Musc blanc || مسك أبيض',
                ],
                'delivery_info' => 'Livraison gratuite || توصيل مجاني',
                'return_policy' => 'Retour sous 7 jours si non ouvert || إرجاع خلال 7 أيام إذا كان المنتج غير مفتوح',
                'authenticity_guarantee' => 'Parfum 100% authentique garanti || عطر أصلي 100% مضمون',
                'is_best_seller' => true,
                'is_trending' => true,
                'discount_percentage' => 0,
                'similar_slugs' => ['dolce-gabbana-light-blue', 'invictus'],
                'is_active' => true,
            ],
            [
                'name' => 'Wanted',
                'slug' => 'azzaro-wanted',
                'brand' => 'Azzaro',
                'gender' => 'Homme || رجالي',
                'short_description' => 'Oriental boise epice. || شرقي خشبي متبّل.',
                'description' => 'Energique et seduisant, ideal pour le soir. || حيوي وجذاب، مثالي للمساء.',
                'price' => 69.00,
                'image_url' => null,
                'country_of_origin' => 'France || فرنسا',
                'size_options' => ['20ml', '30ml', '50ml'],
                'stock_status' => 'En stock || متوفر',
                'fragrance_family' => 'Oriental boise epice || شرقي خشبي متبّل',
                'recipe' => 'Epices lumineuses et base tonka ambree. || توابل مضيئة وقاعدة تونكا عنبرية.',
                'top_notes' => ['Citron || ليمون', 'Gingembre || زنجبيل', 'Lavande || لافندر'],
                'heart_notes' => ['Cardamome || هيل', 'Genievre || العرعر', 'Pomme || تفاح'],
                'base_notes' => ['Feve tonka || حبوب التونكا', 'Ambre boise || عنبر خشبي', 'Vetiver || فيتيفر'],
                'longevity' => '7-9 heures || 7-9 ساعات',
                'sillage' => 'Fort || فواح',
                'vibe' => 'Festif || احتفالي',
                'when_to_wear' => 'Soiree || المساء',
                'feeling' => 'Audace || جرأة',
                'average_rating' => 4.5,
                'reviews_count' => 120,
                'reviews' => [],
                'bottle_images' => [null],
                'packaging_images' => [null],
                'lifestyle_images' => [null],
                'ingredients' => [
                    'Citron || ليمون',
                    'Gingembre || زنجبيل',
                    'Lavande || لافندر',
                    'Cardamome || هيل',
                    'Genievre || العرعر',
                    'Pomme || تفاح',
                    'Feve tonka || حبوب التونكا',
                    'Ambre boise || عنبر خشبي',
                    'Vetiver || فيتيفر',
                ],
                'delivery_info' => 'Livraison gratuite || توصيل مجاني',
                'return_policy' => 'Retour sous 7 jours si non ouvert || إرجاع خلال 7 أيام إذا كان المنتج غير مفتوح',
                'authenticity_guarantee' => 'Parfum 100% authentique garanti || عطر أصلي 100% مضمون',
                'is_best_seller' => true,
                'is_trending' => true,
                'discount_percentage' => 0,
                'similar_slugs' => ['boss-bottled', 'dior-sauvage'],
                'is_active' => true,
            ],
            [
                'name' => 'Imagination',
                'slug' => 'imagination',
                'brand' => 'Louis Vuitton',
                'gender' => 'Homme || رجالي',
                'short_description' => 'Aromatique citronne et propre. || عطري حمضي نظيف.',
                'description' => 'Elegance moderne avec agrumes et bois doux. || أناقة عصرية مع حمضيات وأخشاب ناعمة.',
                'price' => 69.00,
                'image_url' => null,
                'country_of_origin' => 'France || فرنسا',
                'size_options' => ['20ml', '30ml', '50ml'],
                'stock_status' => 'En stock || متوفر',
                'fragrance_family' => 'Aromatique citrus boise || عطري حمضي خشبي',
                'recipe' => 'Citron et the noir sur fond boise. || ليمون وشاي أسود على قاعدة خشبية.',
                'top_notes' => ['Bergamote || برغموت', 'Orange || برتقال', 'Citron || ليمون'],
                'heart_notes' => ['The noir || شاي أسود', 'Gingembre || زنجبيل', 'Neroli || نيرولي'],
                'base_notes' => ['Ambre || عنبر', 'Encens || بخور', 'Bois de gaiac || خشب الغاياك'],
                'longevity' => '7-9 heures || 7-9 ساعات',
                'sillage' => 'Modere || متوسط',
                'vibe' => 'Raffine || راقٍ',
                'when_to_wear' => 'Jour et soiree || النهار والمساء',
                'feeling' => 'Confiance || ثقة',
                'average_rating' => 4.7,
                'reviews_count' => 95,
                'reviews' => [],
                'bottle_images' => [null],
                'packaging_images' => [null],
                'lifestyle_images' => [null],
                'ingredients' => [
                    'Bergamote || برغموت',
                    'Orange || برتقال',
                    'Citron || ليمون',
                    'The noir || شاي أسود',
                    'Gingembre || زنجبيل',
                    'Neroli || نيرولي',
                    'Ambre || عنبر',
                    'Encens || بخور',
                    'Bois de gaiac || خشب الغاياك',
                ],
                'delivery_info' => 'Livraison gratuite || توصيل مجاني',
                'return_policy' => 'Retour sous 7 jours si non ouvert || إرجاع خلال 7 أيام إذا كان المنتج غير مفتوح',
                'authenticity_guarantee' => 'Parfum 100% authentique garanti || عطر أصلي 100% مضمون',
                'is_best_seller' => true,
                'is_trending' => true,
                'discount_percentage' => 0,
                'similar_slugs' => ['y-eau-de-parfum', 'bleu-chanel'],
                'is_active' => true,
            ],
            [
                'name' => 'Eros',
                'slug' => 'versace-eros',
                'brand' => 'Versace',
                'gender' => 'Homme || رجالي',
                'short_description' => 'Oriental aromatique seduisant. || شرقي عطري جذاب.',
                'description' => 'Menthe, vanille et bois pour un style puissant. || نعناع وفانيلا وأخشاب بأسلوب قوي.',
                'price' => 69.00,
                'image_url' => null,
                'country_of_origin' => 'Italie || إيطاليا',
                'size_options' => ['20ml', '30ml', '50ml'],
                'stock_status' => 'En stock || متوفر',
                'fragrance_family' => 'Oriental aromatique || شرقي عطري',
                'recipe' => 'Menthe et vanille sur fond boise. || نعناع وفانيلا على قاعدة خشبية.',
                'top_notes' => ['Menthe || نعناع', 'Pomme verte || تفاح أخضر', 'Citron || ليمون'],
                'heart_notes' => ['Feve tonka || حبوب التونكا', 'Geranium || إبرة الراعي', 'Ambroxan || أمبروكسان'],
                'base_notes' => ['Vanille || فانيلا', 'Cedre || خشب الأرز', 'Vetiver || فيتيفر', 'Mousse de chene || طحلب البلوط'],
                'longevity' => '8-10 heures || 8-10 ساعات',
                'sillage' => 'Fort || فواح',
                'vibe' => 'Energique || حيوي',
                'when_to_wear' => 'Soiree || المساء',
                'feeling' => 'Charisme || كاريزما',
                'average_rating' => 4.7,
                'reviews_count' => 135,
                'reviews' => [],
                'bottle_images' => [null],
                'packaging_images' => [null],
                'lifestyle_images' => [null],
                'ingredients' => [
                    'Menthe || نعناع',
                    'Pomme verte || تفاح أخضر',
                    'Citron || ليمون',
                    'Feve tonka || حبوب التونكا',
                    'Geranium || إبرة الراعي',
                    'Ambroxan || أمبروكسان',
                    'Vanille || فانيلا',
                    'Cedre || خشب الأرز',
                    'Vetiver || فيتيفر',
                    'Mousse de chene || طحلب البلوط',
                ],
                'delivery_info' => 'Livraison gratuite || توصيل مجاني',
                'return_policy' => 'Retour sous 7 jours si non ouvert || إرجاع خلال 7 أيام إذا كان المنتج غير مفتوح',
                'authenticity_guarantee' => 'Parfum 100% authentique garanti || عطر أصلي 100% مضمون',
                'is_best_seller' => true,
                'is_trending' => true,
                'discount_percentage' => 0,
                'similar_slugs' => ['dior-sauvage', 'boss-bottled'],
                'is_active' => true,
            ],
            [
                'name' => 'Invictus',
                'slug' => 'invictus',
                'brand' => 'Paco Rabanne',
                'gender' => 'Homme || رجالي',
                'short_description' => 'Aquatique boise sportif. || مائي خشبي رياضي.',
                'description' => 'Frais, energique et dynamique. || منعش وحيوي وديناميكي.',
                'price' => 69.00,
                'image_url' => null,
                'country_of_origin' => 'France || فرنسا',
                'size_options' => ['20ml', '30ml', '50ml'],
                'stock_status' => 'En stock || متوفر',
                'fragrance_family' => 'Aquatique boise || مائي خشبي',
                'recipe' => 'Notes marines et bois secs. || نغمات بحرية وأخشاب جافة.',
                'top_notes' => ['Pamplemousse || جريب فروت', 'Notes marines || نغمات بحرية', 'Mandarine || يوسفي'],
                'heart_notes' => ['Feuille de laurier || ورق الغار', 'Jasmin || ياسمين'],
                'base_notes' => ['Bois de gaiac || خشب الغاياك', 'Patchouli || باتشولي', 'Ambre gris || عنبر رمادي'],
                'longevity' => '6-8 heures || 6-8 ساعات',
                'sillage' => 'Modere || متوسط',
                'vibe' => 'Sportif || رياضي',
                'when_to_wear' => 'Journee || النهار',
                'feeling' => 'Energie || طاقة',
                'average_rating' => 4.5,
                'reviews_count' => 125,
                'reviews' => [],
                'bottle_images' => [null],
                'packaging_images' => [null],
                'lifestyle_images' => [null],
                'ingredients' => [
                    'Pamplemousse || جريب فروت',
                    'Notes marines || نغمات بحرية',
                    'Mandarine || يوسفي',
                    'Feuille de laurier || ورق الغار',
                    'Jasmin || ياسمين',
                    'Bois de gaiac || خشب الغاياك',
                    'Patchouli || باتشولي',
                    'Ambre gris || عنبر رمادي',
                ],
                'delivery_info' => 'Livraison gratuite || توصيل مجاني',
                'return_policy' => 'Retour sous 7 jours si non ouvert || إرجاع خلال 7 أيام إذا كان المنتج غير مفتوح',
                'authenticity_guarantee' => 'Parfum 100% authentique garanti || عطر أصلي 100% مضمون',
                'is_best_seller' => true,
                'is_trending' => true,
                'discount_percentage' => 0,
                'similar_slugs' => ['acqua-di-gio', 'dior-sauvage'],
                'is_active' => true,
            ],
        ];

        Perfume::query()->delete();

        foreach ($perfumes as $perfume) {
            Perfume::create($perfume);
        }
    }
}
